<a href="https://colab.research.google.com/github/urfa10/MSIB_Dasar-Python/blob/main/session_3_package_basic_pemrograman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Py Boxes

## Module : datetime

In [ ]:
import datetime

In [ ]:
# Mengambil date saat kode ini dijalankan
today = datetime.datetime.now()
print(today)
today_2 = datetime.date.today()
print(today_2)

2023-06-13 16:49:05.090290
2023-06-13


In [ ]:
print(type(today))
print(type(today_2))

<class 'datetime.datetime'>
<class 'datetime.date'>


In [ ]:
# Mengubah bentuk dari date menjadi string
today.strftime('%d-%m-%Y')

'13-06-2023'

In [ ]:
today.strftime('%A, %d %B %Y')

'Tuesday, 13 June 2023'

In [ ]:
# mengambil part dari date
year = today.year
month = today.month
day = today.day

print(f'Hari ini tahun {year} bulan {month} tanggal {day}')

Hari ini tahun 2023 bulan 6 tanggal 13


In [ ]:
# Membuat objek date
tanggal_lahir = datetime.datetime(2000, 10, 10)
print(tanggal_lahir)

2000-10-10 00:00:00


## Library : Numpy

In [ ]:
# import library
import numpy as np

In [ ]:
# Membuat array
x = np.array(50)
y = np.array('Uzumaki Naruto')
bilangan_genap = np.array([2, 4, 6, 8, 10])
bilangan_ganjil = np.array([1, 3, 5, 7, 9])
print(bilangan_ganjil)
print(bilangan_genap)
y

[1 3 5 7 9]
[ 2  4  6  8 10]


array('Uzumaki Naruto', dtype='<U14')

In [ ]:
# Multidimensional array
bilangan = np.array([[2, 4, 6, 8, 10],
                     [1, 3, 5, 7, 9]]) # dimensi array 2 x 5 (2 baris dan 5 kolom)
bilangan

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
nomor = np.array([[2, 4, 6, 8],
                  [1, 3, 5, 7, 9]])
nomor

<ipython-input-39-74eb6283de63>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nomor = np.array([[2, 4, 6, 8],


array([list([2, 4, 6, 8]), list([1, 3, 5, 7, 9])], dtype=object)

In [ ]:
# Perbedaan array dengan list
list_bilangan_genap = [2, 4, 6, 8, 10]

print(list_bilangan_genap * 2)
print(bilangan_genap * 2)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
[ 4  8 12 16 20]


In [ ]:
print(list_bilangan_genap)
print(bilangan_genap + 2)

[2, 4, 6, 8, 10]
[ 4  6  8 10 12]


In [ ]:
# Operasi array
nilai_mahasiswa = np.array([90, 97, 50, 45, 80, 86, 77, 100, 20])
list_nilai_mahasiswa = [90, 97, 50, 45, 80, 86, 77, 100, 20]

In [ ]:
print(np.sum(nilai_mahasiswa))
print(sum(list_nilai_mahasiswa))

645
645


In [ ]:
print(np.min(nilai_mahasiswa))
print(min(list_nilai_mahasiswa))

20
20


In [ ]:
print(np.mean(nilai_mahasiswa))
# print(mean(list_nilai_mahasiswa))

71.66666666666667


In [ ]:
print(np.median(nilai_mahasiswa))
# print(median(list_nilai_mahasiswa))

80.0


In [ ]:
print(np.log10(nilai_mahasiswa))

[1.95424251 1.98677173 1.69897    1.65321251 1.90308999 1.93449845
 1.88649073 2.         1.30103   ]


In [ ]:
# mengubah dimensi array
print(nilai_mahasiswa) # (1 x 9)
print(nilai_mahasiswa.reshape(3, 3))

[ 90  97  50  45  80  86  77 100  20]
[[ 90  97  50]
 [ 45  80  86]
 [ 77 100  20]]


In [ ]:
# Challenge Time (Riski Wahyu Ningsih)
nilai_1 = [80, 87, 91]
nilai_2 = [77, 65, 75]
nilai_3 = [59, 60, 47]

nilai = np.array([nilai_1, nilai_2, nilai_3])
print(nilai)

nilai_reshape = nilai.reshape(1,9)
# nilai.reshape(-1)
print(nilai_reshape)

print(np.mean(nilai_reshape) > np.median(nilai_reshape))


[[80 87 91]
 [77 65 75]
 [59 60 47]]
[[80 87 91 77 65 75 59 60 47]]
False


# Programming Basic
## Conditional Statement

In [ ]:
# implementasi 1 kondisi
current_status = 'on-delivery'
barang_diterima = True

if barang_diterima == True:
  current_status = 'delivered'

print(current_status)

delivered


In [ ]:
# implementasi 2 kondisi
x = 15

if x > 5:
  print('x lebih besar dari 5')
else:
  print('x tidak lebih besar dari 5')

x lebih besar dari 5


In [ ]:
# implementasi 3 kondisi
x = -100

if x > 10:
  print('x lebih besar dari 10')
elif x == 10:
  print('x sama dengan 10')
else:
  print('x lebih kecil dari 10')

x lebih kecil dari 10


In [ ]:
# Challenge
nilai = [90, 85, 55, 47, 87, 90, 65]

# ingin mengklasifikasikan rata-rata dari nilai tersebut
# jika rata-rata >= 90 maka rapot = 'A'
# jika rata-rata >= 80 maka rapot = 'B'
# jika rata-rata >= 70 maka rapot = 'C'
# jika rata-rata >= 60 maka rapot = 'D'
# jika rata-rata < 60 maka rapot = 'E'

# print(nilai rata-rata)
# print(nilai rapot)

# jawaban dari laureta mauren
rata_rata = sum(nilai) / len(nilai)

if rata_rata >= 90:
  rapot = 'A'
elif rata_rata >= 80:
  rapot = 'B'
elif rata_rata >= 70:
  rapot = 'C'
elif rata_rata >= 60:
  rapot = 'D'
else:
  rapot = 'E'

print(f'nilai rata-rata: {rata_rata}')
print(f'nilai rapot: {rapot}')

nilai rata-rata: 74.14285714285714
nilai rapot: C


In [ ]:
# Nested IF
prefered_genre = 'anime'
wacth_ads = True

if prefered_genre == 'drama':
  if wacth_ads:
    service = 'service a (with ads)'
  else:
    service = 'service b (no ads)'
elif prefered_genre == 'action':
  if wacth_ads:
    service = 'service c (with ads)'
  else:
    service = 'service d (no ads)'
else:
  service = 'service e'

print(f'prefered genre: {prefered_genre}')
print(f'wacth ads: {wacth_ads}')
print(f'streaming service: {service}')

prefered genre: anime
wacth ads: True
streaming service: service e


In [ ]:
x=14
y=16

print(x>14 & x==y)

False


In [ ]:
# tenary operator / one line conditional statement
age = 20

discount_eligible = 'Yes' if age >=60 else 'No'

print(f'age: {age} is eligible for discount: {discount_eligible}')

age: 20 is eligible for discount: No


In [ ]:
# number = 42
# gunakan one line conditional statement untuk menentukan number itu genap atau ganjil
# Jawaban dari riski wahyu ningsih
number = 42
bilangan = 'genap' if number % 2 == 0 else 'ganjil'
print(f'number: {number} adalah bilangan {bilangan}')

number: 42 adalah bilangan genap


In [ ]:
temp = int(input('masukan nilai temperature dalam celcius: '))

if temp < 0:
  classification = 'Freezing'
elif temp < 10:
  classification = 'Cold'
elif temp < 20:
  classification = 'Mild'
elif temp < 30:
  classification = 'Warm'
else:
  classification = 'Bekasi'

print(f'{temp}C is {classification}')

masukan nilai temperature dalam celcius: 60
60C is Bekasi


In [ ]:
# Challenge
usia = int(input('masukan usia anda: '))
genre = input('pilih genre favorit anda (action atau romance): ').lower()
iklan = input('apakah bersedia menonton iklan (ya atau tidak): ').lower()

if iklan == 'ya':
  rekomendasi = 'Layanan E'
elif usia < 18:
  if genre == 'action':
    rekomendasi = 'Layanan A'
  elif genre == 'romance':
    rekomendasi = 'Layanan B'
  else:
    rekomendasi = 'Layanan F'
else:
  if genre == 'action':
    rekomendasi = 'Layanan C'
  elif genre == 'romance':
    rekomendasi = 'Layanan D'
  else:
    rekomendasi = 'Layanan F'

print(f'Layanan streaming yang direkomendasikan: {rekomendasi}')

masukan usia anda: 70
pilih genre favorit anda (action atau romance): romance
apakah bersedia menonton iklan (ya atau tidak): ya
Layanan streaming yang direkomendasikan: Layanan E
